name: Containerization CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21 '
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mvn docker:build

      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $username -p $password

      - name: push images to docker hub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/ccebe:latest